version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: hungkodak
       MYSQL_DATABASE: store
       MYSQL_USER: admin
       MYSQL_PASSWORD: nop@ss   
     ports:
       - "3306:3306"
volumes:
    db_data: